// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http_error.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpError) Reset()         { *m = HttpError{} }
func (m *HttpError) String() string { return proto.CompactTextString(m) }
func (*HttpError) ProtoMessage()    {}
func (*HttpError) Descriptor() ([]byte, []int) {
	return fileDescriptor_f89808e2956c2911, []int{0}
}

func (m *HttpError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpError.Unmarshal(m, b)
}
func (m *HttpError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpError.Marshal(b, m, deterministic)
}
func (m *HttpError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpError.Merge(m, src)
}
func (m *HttpError) XXX_Size() int {
	return xxx_messageInfo_HttpError.Size(m)
}
func (m *HttpError) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpError.DiscardUnknown(m)
}

var xxx_messageInfo_HttpError proto.InternalMessageInfo

func (m *HttpError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HttpError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HttpError)(nil), "protobuf.HttpError")
}

func init() { proto.RegisterFile("http_error.proto", fileDescriptor_f89808e2956c2911) }

var fileDescriptor_f89808e2956c2911 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x28, 0x29, 0x29,
	0x88, 0x4f, 0x2d, 0x2a, 0xca, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0x49, 0xa5, 0x69, 0x4a, 0x96, 0x5c, 0x9c, 0x1e, 0x25, 0x25, 0x05, 0xae, 0x20, 0x49, 0x21, 0x21,
	0x2e, 0x96, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x30, 0x5b, 0x48,
	0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33,
	0x08, 0xc6, 0x4d, 0x62, 0x03, 0x1b, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x19, 0x9f, 0x2d,
	0xf1, 0x5f, 0x00, 0x00, 0x00,
}
