.TH "VIRGIL" "1" "October 14, 2015" "Virgil Security CLI (1.0.0)" "BSD General Commands Manual"
.SH NAME
\f[B]container-auth\f[] -- authenticate a session.

.SH SYNOPSIS
\f[B]virgil container-auth\f[] 
[\-\-user-id \f[I]arg\f[]]
[\-\-container-pwd \f[I]arg\f[]]

.SH DESCRIPTION
Authenticate a session. Virgil\[aq]s Service will create an Authentication token
that will be available for 60 minutes. If you work longer than 60 minutes, 
the token will automatically prolong itself.  Otherwise, the token will die 
and you will need to generate a new one.
.TP
Note:  Before logging in, make sure that you have already initialized the 
Container  in Virgil\[aq]s Private Key service. Use the same confirmed User Data
identity parameter as you registered in our Public Keys service.

.SH OPTIONS
.B \-u \f[I]arg\f[]  \-\-user-id \f[I]arg\f[]
User\[aq]s identifer.

.RS
.PP
Format: [email|phone|domain]:<value>
.PD 0
.P
.PD
where:
.IP \[bu] 2
if email, then \- user\[aq]s email;
.IP \[bu] 2
if phone, then \- user\[aq]s phone;
.IP \[bu] 2
if domain, then \- user\[aq]s domain.
.RE

.TP
.B \-c \f[I]arg\f[], \-\-container-pwd \f[I]arg\f[]
Container password.

.SH SEE ALSO
\f[C]container-del(1)\f[], \f[C]container-info(1)\f[], \f[C]container-update(1)\f[],
\f[C]private-key-add(1)\f[], \f[C]private-key-del(1)\f[], \f[C]private-key-get(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.