.TH "VIRGIL" "1" "October 14, 2015" "Virgil Security CLI (1.0.0)" "BSD General Commands Manual"
.SH NAME
\f[B]container-info\f[] -- get container-type: easy | normal.

.SH SYNOPSIS
\f[B]virgil container-info\f[] 
[\-\-public-key-id \f[I]arg\f[]]

.SH DESCRIPTION
Get container-type: easy | normal.

.SH OPTIONS
.B \-e \f[I]arg\f[], \-\-public-key-id \f[I]arg\f[]
Virgil Public Key.

.RS
.PP
.RB Format: [public-id|email|phone|domain]:<value>
.PD 0
.P
.PD
where:
.IP \[bu] 2
if public-id, then \- user\[aq]s public-key-id;
.IP \[bu] 2
if email, then \- user\[aq]s email;
.IP \[bu] 2
if phone, then \- user\[aq]s phone;
.IP \[bu] 2
if domain, then \- user\[aq]s domain.
.RE

.SH SEE ALSO
\f[C]virgil(1)\f[], \f[C]virgilkeygen(1)\f[], \f[C]virgilkeyget(1)\f[],
\f[C]virgilconfirm(1)\f[]

.SH AUTHORS
(c) Virgil Security Inc.