.TH "VIRGIL" "1" "October 14, 2015" "Virgil Security CLI (1.0.0)" "BSD General Commands Manual"
.SH NAME
\f[B]container-confirm\f[] -- confirm password token and re-encrypt Private Key data with the new password. 

.SH SYNOPSIS
\f[B]virgil container-confirm\f[] 
[\-\-confirmation-token \f[I]arg\f[]]

.SH DESCRIPTION
Confirm password token and re-encrypt Private Key data with the new password. 

.SH OPTIONS
.B \-t \f[I]arg\f[], \-\-confirmation-token \f[I]arg\f[]
Confirmation token received on email box.

.SH SEE ALSO
\f[C]container-reset(1)\f[]

.SH AUTHORS
(c) Virgil Security Inc.