.TH "VIRGIL" "1" "October 14, 2015" "Virgil Security CLI (1.0.0)" "BSD General Commands Manual"
.SH NAME
\f[B]private-key-info\f[] \-\- get public key from the private key

.SH SYNOPSIS
\f[B]virgil private-key-info\f[] [\-\-in \f[I]file\f[]] [\-\-out \f[I]file\f[]]
[\-\-private-pwd \f[I]arg\f[]]

.SH DESCRIPTION
Get public key from the private key.

.SH OPTIONS
.B \-i \f[I]file\f[], \-\-in \f[I]file\f[]
Private key.
If omitted stdin is used.

.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Public key.
If omitted stdout is used.

.TP
.B \-p \f[I]arg\f[], \-\-private-pwd \f[I]arg\f[]
Private key password.

.SH SEE ALSO
\f[C]virgil(1)\f[], \f[C]virgilkeygen(1)\f[]

.SH AUTHORS
(c) Virgil Security Inc.