.TH "VIRGIL" "1" "October 14, 2015""Virgil Security CLI (1.0.0)" "BSD General Commands Manual"
.SH NAME
\f[B]sign\f[] \-\- sign data.

.SH SYNOPSIS
\f[B]virgil sign\f[] [\-\-in \f[I]file\f[]] [\-\-out \f[I]file\f[]]
\-\-key \f[I]file\f[] [\-\-pwd \f[I]arg\f[]]

.SH DESCRIPTION
Sign data with given user\[aq]s private key.

.SH OPTIONS
.B \-i \f[I]file\f[], \-\-in \f[I]file\f[]
Data to be signed.
If omitted stdin is used.

.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Digest sign.
If omitted stdout is used.

.TP
.B \-k \f[I]file\f[], \-\-key \f[I]file\f[]
Signer\[aq]s private key.

.TP
.B \-p \f[I]arg\f[], \-\-pwd \f[I]arg\f[]
Signer\[aq]s private key password.

.SH SEE ALSO
\f[C]virgil(1)\f[], \f[C]virgilverify(1)\f[]

.SH AUTHORS
(c) Virgil Security Inc.