.Dd April 22, 2015
.Dt KEY2PUB 1
.Os Darwin
.Sh NAME
.Nm key2pub
.Nd extract public key from the private key
.Sh SYNOPSIS
.Nm
.Op Fl Fl in Ar file
.Op Fl Fl out Ar file
.Op Fl Fl pwd Ar arg
.Sh DESCRIPTION
Extract public key from the private key.
.Sh OPTIONS
.Bl -tag -width "--"
.It Fl i, Fl Fl in Ar file
Private key. If omitted \fBstdin\fP is used.
.It Fl o, Fl Fl out Ar file
Public key. If omitted \fBstdout\fP is used.
.It Fl p, Fl Fl pwd Ar arg
Private key password.
.El
.Sh SEE ALSO
.Xr virgil 1 ,
.Xr virgilpub2cert 1 ,
.Xr virgilkeygen 1
