.TH "VIRGIL" "1" "August 01, 2015" "Virgil Security CLI (0.3.0)" "BSD General Commands Manual"
.SH NAME
.PP
\f[B]verify\f[] \-\- verify data.
.SH SYNOPSIS
.PP
\f[B]virgil verify\f[] [\-\-in \f[I]file\f[]] [\-\-out \f[I]file\f[]]
\-\-sign \f[I]file\f[] \-\-sign\-owner \f[I]arg\f[]
.SH DESCRIPTION
.PP
Verify data with given user\[aq]s identifier or with it Virgil Public
Key.
.SH OPTIONS
.TP
.B \-i \f[I]file\f[], \-\-in \f[I]file\f[]
Data to be verified.
If omitted stdin is used.
.RS
.RE
.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Verification result: \f[C]success\f[] | \f[C]failure\f[].
If omitted stdout is used.
.RS
.RE
.TP
.B \-s \f[I]file\f[], \-\-sign \f[I]file\f[]
(required) Digest sign.
.RS
.RE
.TP
.B \-r \f[I]arg\f[], \-\-sign\-owner \f[I]arg\f[]
(required) Sign owner, defined in format:
.RS
.IP
.nf
\f[C]
[file|email|phone|domain]:<value>
\f[]
.fi
.PP
where:
.IP \[bu] 2
if \f[C]file\f[], then \f[I]value\f[] \- signers\[aq]s Virgil Public Key
file stored locally;
.IP \[bu] 2
if \f[C]email\f[], then \f[I]value\f[] \- signers\[aq]s email;
.IP \[bu] 2
if \f[C]phone\f[], then \f[I]value\f[] \- signers\[aq]s phone;
.IP \[bu] 2
if \f[C]domain\f[], then \f[I]value\f[] \- signers\[aq]s domain.
.RE
.SH SEE ALSO
.PP
\f[C]virgil(1)\f[], \f[C]virgilsign(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.
