.TH "VIRGIL" "1" "August 01, 2015" "Virgil Security CLI (0.3.0)" "BSD General Commands Manual"
.SH NAME
.PP
\f[B]virgil\f[] \-\- command line tool for using Virgil Security stack
functionality.
.SH SYNOPSIS
.PP
\f[B]virgil\f[] \f[I]command\f[] [\f[I]command_opts\f[]]
[\f[I]command_args\f[]]
.SH DESCRIPTION
.PP
The \f[B]virgil\f[] program is a command line tool for using Virgil
Security stack functionality.
It can be used to encrypt, decrypt, sign and verify data.
Functionality also includes interaction with Virgil Public Keys Service.
.SH COMMANDS
.TP
.B \f[B]keygen\f[]
Generate private key with a given parameters.
For example:
.RS
.IP
.nf
\f[C]
virgil\ keygen\ \-o\ user.key
\f[]
.fi
.RE
.TP
.B \f[B]key2pub\f[]
Get public key from the private key.
For example:
.RS
.IP
.nf
\f[C]
virgil\ key2pub\ \-i\ user.key\ \-o\ user.pub
\f[]
.fi
.RE
.TP
.B \f[B]keyreg\f[]
Register user\[aq]s public key on the Virgil Public Keys service.
For example:
.RS
.IP
.nf
\f[C]
virgil\ keyreg\ \-i\ user.pub\ \-o\ user.pk\ email:user\@domain.com
\f[]
.fi
.RE
.TP
.B \f[B]keyget\f[]
Get user\[aq]s public key from the Virgil Public Keys service.
For example:
.RS
.IP
.nf
\f[C]
virgil\ keyget\ \-o\ user.pk\ email:user\@domain.com
\f[]
.fi
.RE
.TP
.B \f[B]confirm\f[]
Send confirmation code to the Virgil Public Keys service.
For example:
.RS
.IP
.nf
\f[C]
virgil\ confirm\ \-i\ email:user\@domain.com\ \-c\ E5J8W7
\f[]
.fi
.RE
.TP
.B \f[B]reconfirm\f[]
Resend confirmation code to the user for given user\[aq]s identifier.
For example:
.RS
.IP
.nf
\f[C]
virgil\ reconfirm\ \-i\ email:user\@domain.com
\f[]
.fi
.RE
.TP
.B \f[B]encrypt\f[]
Encrypt data for given recipients which can be defined by Virgil Public
Keys and by passwords.
For example:
.RS
.IP
.nf
\f[C]
virgil\ encrypt\ \-i\ plain.txt\ \-o\ encrypted.dat\ email:user\@domain.com
\f[]
.fi
.RE
.TP
.B \f[B]decrypt\f[]
Decrypt data for given recipient which can be defined by Virgil Public
Key or by password.
For example:
.RS
.IP
.nf
\f[C]
virgil\ decrypt\ \-i\ encrypted.dat\ \-o\ plain.txt\ \-k\ user.key\ \-r\ user.pk
\f[]
.fi
.RE
.TP
.B \f[B]sign\f[]
Sign data with Private Key.
For example:
.RS
.IP
.nf
\f[C]
virgil\ sign\ \-i\ plain.txt\ \-o\ plain.txt.sign\ \-k\ user.key
\f[]
.fi
.RE
.TP
.B \f[B]verify\f[]
Verify data with Virgil Public Key.
For example:
.RS
.IP
.nf
\f[C]
virgil\ verify\ \-i\ plain.txt\ \-s\ plain.txt.sign\ \-r\ key:user.pk
virgil\ verify\ \-i\ plain.txt\ \-s\ plain.txt.sign\ \-r\ email:user\@domain.com
\f[]
.fi
.RE
.SH SEE ALSO
.PP
\f[C]virgilkeygen(1)\f[], \f[C]virgilkey2pub(1)\f[],
\f[C]virgilkeyreg(1)\f[], \f[C]virgilkeyget(1)\f[],
.PD 0
.P
.PD
\f[C]virgilconfirm(1)\f[], \f[C]virgilreconfirm(1)\f[],
.PD 0
.P
.PD
\f[C]virgilencrypt(1)\f[], \f[C]virgildecrypt(1)\f[],
.PD 0
.P
.PD
\f[C]virgilsign(1)\f[], \f[C]virgilverify(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.
