.TH "VIRGIL" "1" "August 01, 2015" "Virgil Security CLI (0.3.0)" "BSD General Commands Manual"
.SH NAME
.PP
\f[B]sign\f[] \-\- sign data.
.SH SYNOPSIS
.PP
\f[B]virgil sign\f[] [\-\-in \f[I]file\f[]] [\-\-out \f[I]file\f[]]
\-\-key \f[I]file\f[] [\-\-pwd \f[I]arg\f[]]
.SH DESCRIPTION
.PP
Sign data with given user\[aq]s private key.
.SH OPTIONS
.TP
.B \-i \f[I]file\f[], \-\-in \f[I]file\f[]
Data to be signed.
If omitted stdin is used.
.RS
.RE
.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Digest sign.
If omitted stdout is used.
.RS
.RE
.TP
.B \-k \f[I]file\f[], \-\-key \f[I]file\f[]
Signer\[aq]s private key.
.RS
.RE
.TP
.B \-p \f[I]arg\f[], \-\-pwd \f[I]arg\f[]
Signer\[aq]s private key password.
.RS
.RE
.SH SEE ALSO
.PP
\f[C]virgil(1)\f[], \f[C]virgilverify(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.
