.TH "VIRGIL" "1" "August 01, 2015" "Virgil Security CLI (0.3.0)" "BSD General Commands Manual"
.SH NAME
.PP
\f[B]keyget\f[] \-\- get user\[aq]s Virgil Public Key from the Virgil
Public Keys service.
.SH SYNOPSIS
.PP
\f[B]virgil keyget\f[] [\-\-out \f[I]file\f[]] \f[I]user_id...\f[]
.SH DESCRIPTION
.PP
Get user\[aq]s Virgil Public Key from the Virgil Public Keys service.
.SH OPTIONS
.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Virgil Public Key.
If omitted stdout is used.
.RS
.RE
.TP
.B \f[I]user_id\f[]
(required) User\[aq]s identifer.
.RS
.PP
Format:
.IP
.nf
\f[C]
[email|phone|domain]:<value>
\f[]
.fi
.PP
where:
.IP \[bu] 2
if \f[C]email\f[], then \f[I]value\f[] \- user\[aq]s email;
.IP \[bu] 2
if \f[C]phone\f[], then \f[I]value\f[] \- user\[aq]s phone;
.IP \[bu] 2
if \f[C]domain\f[], then \f[I]value\f[] \- user\[aq]s domain.
.RE
.SH SEE ALSO
.PP
\f[C]virgil(1)\f[], \f[C]virgilkeygen(1)\f[], \f[C]virgilkeyreg(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.
