.Dd April 22, 2015
.Dt GETUSER 1
.Os Darwin
.Sh NAME
.Nm getuser
.Nd get Virgil Public Key from Public Keys Service
.Sh SYNOPSIS
.Nm
.Op Fl Fl in Ar file
.Op Fl Fl out Ar file
.Ar user_id ...
.Sh DESCRIPTION
Get Virgil Public Key from Public Keys Service.
.Sh OPTIONS
.Bl -tag -width "--"
.It Fl o, Fl Fl out Ar file
Virgil Public Key. If omitted \fBstdout\fP is used.
.It user_id
Formatted user's identifer.

Format: [email|phone|domain]:<value>
.Bl -bullet -offset --
.It
email - user's email;
.It
phone - user's phone;
.It
domain - user's domain.
.El
.El
.Sh EXAMPLE
Next command get Virgil Public Key from Public Keys Service.

\fBvirgil getuser -o virgil_public.key email:xxxx@yyyy.com\fR

.Sh SEE ALSO
.Xr virgil 1 ,
.Xr virgiladduser 1
