.TH "VIRGIL" "1" "August 01, 2015" "Virgil Security CLI (0.3.0)" "BSD General Commands Manual"
.SH NAME
.PP
\f[B]key2pub\f[] \-\- get public key from the private key
.SH SYNOPSIS
.PP
\f[B]virgil key2pub\f[] [\-\-in \f[I]file\f[]] [\-\-out \f[I]file\f[]]
[\-\-pwd \f[I]arg\f[]]
.SH DESCRIPTION
.PP
Get public key from the private key.
.SH OPTIONS
.TP
.B \-i \f[I]file\f[], \-\-in \f[I]file\f[]
Private key.
If omitted stdin is used.
.RS
.RE
.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Public key.
If omitted stdout is used.
.RS
.RE
.TP
.B \-p \f[I]arg\f[], \-\-pwd \f[I]arg\f[]
Private key password.
.RS
.RE
.SH SEE ALSO
.PP
\f[C]virgil(1)\f[], \f[C]virgilkeygen(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.
