.Dd April 22, 2015
.Dt VERIFY 1
.Os Darwin
.Sh NAME
.Nm verify
.Nd verify data
.Sh SYNOPSIS
.Nm
.Op Fl Fl in Ar file
.Op Fl Fl out Ar file
.Fl Fl sign Ar file
.Fl Fl sign-owner Ar arg
.Sh DESCRIPTION
Verify data with given sign.
.Sh RETURN VALUES
.Bl -tag -width "--"
.It \fBEXIT_SUCCESS\fP
verification success
.It \fBEXIT_FAILURE\fP
verification failed
.El
.Sh OPTIONS
.Bl -tag -width "--"
.It Fl i, Fl Fl in Ar file
Data to be verified. If omitted \fBstdin\fP is used.
.It Fl o, Fl Fl out
Verification result: \fBsuccess\fP | f\fBailure\fP. If omitted \fBstdout\fP is used.
.It Fl s, Fl Fl sign Ar file
Digest sign.
.It Fl r, Fl Fl sign-owner Ar file
Sign owner, defined as: \fB[email|phone|fax] : <value>\fR, where
.Bl -bullet
.It
email - recipient's email;
.It
phone - recipient's phone;
.It
fax - recipient's fax.
.El
.El
.Sh SEE ALSO
.Xr virgil 1 ,
.Xr virgilsign 1
