.Dd April 22, 2015
.Dt ADDUSER 1
.Os Darwin
.Sh NAME
.Nm adduser
.Nd register user on the Virgil PKI service
.Sh SYNOPSIS
.Nm
.Op Fl Fl in Ar file
.Op Fl Fl out Ar file
.Ar user_id ...
.Sh DESCRIPTION
Register user on the Virgil PKI service.
.Sh OPTIONS
.Bl -tag -width "--"
.It Fl i, Fl Fl in Ar file
Public key. If omitted \fBstdin\fP is used.
.It Fl o, Fl Fl out Ar file
Certificate. If omitted \fBstdout\fP is used.
.It user_id
Formatted user's identifer.

Format: [email|phone|fax] : <value>
.Bl -bullet -offset --
.It
email - user's email;
.It
phone - user's phone;
.It
fax - user's fax.
.El
.El
.Sh EXAMPLE
Next command generate new keys and register user with it on the Virgil PKI service. \
As a side effect last command create user's certificate.

\fBvirgil keygen | tee new.key | virgil key2pub | virgil adduser email:xxxx@yyyy.com -o new.cert\fR

To see all information about created certificate, just run next command:

\fBvirgil certinfo -i new.cert \fR

.Sh SEE ALSO
.Xr virgil 1 ,
.Xr virgilkeygen 1 ,
.Xr virgilkey2pub 1 ,
.Xr virgilcertinfo 1
