.Dd April 22, 2015
.Dt ENCRYPT 1
.Os Darwin
.Sh NAME
.Nm encrypt
.Nd encrypt data for given recipients
.Sh SYNOPSIS
.Nm
.Op Fl Fl in Ar file
.Op Fl Fl out Ar file
.Op Fl Fl content-info Ar file
.Op Fl Fl recipients Ar file | Ar recipient
.Ar ...
.Sh DESCRIPTION
Encrypt data for given recipients. Recipient can be represented either by the password, or by the certificate.
.Sh OPTIONS
.Bl -tag -width "--"
.It Fl i, Fl Fl in Ar file
Data to be encrypted. If omitted \fBstdin\fP is used.
.It Fl o, Fl Fl out Ar file
Encrypted data. If omitted \fBstdout\fP is used.
.It Fl c, Fl Fl content-info Ar file
Content info. If omitted - becomes a part of the encrypted data.
.It Fl r, Fl Fl recipients Ar file
File that contains information about recipients. Each line can be either empty line, or comment line, or recipient.
.Bd -literal
\fBFormat\fP:
# <comment line> | <certfifcate path> | <password>
.Ed
.Bd -literal
\fBExample\fP:
# Recipients defined by certificates:
cert:~/certificates/cert1.der
cert:~/certificates/cert2.json
# Recipients defined by passwords:
pass:user1_password
pass:user2_password
# Recipients defined by user identifier:
email:test@test.com
phone:+1 777 666 5555
fax:+1 777 999 4444
.Ed
.It Ar recipient
Format: [cert|pass|email|phone|fax]:<value>
.Bl -bullet
.It 
cert:<value> - path to the recipient's certificate file;
.It 
pass:<value> - recipient's password;
.It 
email|phone|fax:<value> - recipient's identifier.
.El
.El
.Sh SEE ALSO
.Xr virgil 1 ,
.Xr virgildecrypt 1
