.TH "VIRGIL" "1" "August 01, 2015" "Virgil Security CLI (0.3.0)" "BSD General Commands Manual"
.SH NAME
.PP
\f[B]keygen\f[] \-\- generate private key with given parameters.
.SH SYNOPSIS
.PP
\f[B]virgil keygen\f[] [\-\-ec \f[I]curve\f[] | \-\-rsa \f[I]nbits\f[]]
[\-\-out \f[I]file\f[]] [\-\-pwd \f[I]arg\f[]] [\-\-format \f[I]arg\f[]]
.SH DESCRIPTION
.PP
Generate private key with given parameters.
.SH OPTIONS
.TP
.B \-e \f[I]curve\f[], \-\-ec \f[I]curve\f[]
Generate elliptic curve key with one of the following curves:
.RS
.IP \[bu] 2
\f[C]bp256r1\f[] \- 256\-bits Brainpool curve;
.IP \[bu] 2
\f[C]bp384r1\f[] \- 384\-bits Brainpool curve;
.IP \[bu] 2
\f[C]bp512r1\f[] \- 512\-bits Brainpool curve (default);
.IP \[bu] 2
\f[C]secp192r1\f[] \- 192\-bits NIST curve;
.IP \[bu] 2
\f[C]secp224r1\f[] \- 224\-bits NIST curve;
.IP \[bu] 2
\f[C]secp256r1\f[] \- 256\-bits NIST curve;
.IP \[bu] 2
\f[C]secp384r1\f[] \- 384\-bits NIST curve;
.IP \[bu] 2
\f[C]secp521r1\f[] \- 521\-bits NIST curve;
.IP \[bu] 2
\f[C]secp192k1\f[] \- 192\-bits "Koblitz" curve;
.IP \[bu] 2
\f[C]secp224k1\f[] \- 224\-bits "Koblitz" curve;
.IP \[bu] 2
\f[C]secp256k1\f[] \- 256\-bits "Koblitz" curve.
.RE
.TP
.B \-r \f[I]nbits\f[], \-\-rsa \f[I]nbits\f[]
Generate RSA key with a given number of bits.
.RS
.RE
.TP
.B \-o \f[I]file\f[], \-\-out \f[I]file\f[]
Private key.
If omitted stdout is used.
.RS
.RE
.TP
.B \-p \f[I]arg\f[], \-\-pwd \f[I]arg\f[]
Password to be used for private key encryption.
If omitted private key is stored in the plain format.
.RS
.RE
.SH SEE ALSO
.PP
\f[C]virgil(1)\f[], \f[C]virgilkey2pub(1)\f[]
.SH AUTHORS
(c) Virgil Security Inc.
